export default {
  loginImage: require("../assets/images/login.png"),
  registerImage: require("../assets/images/register.png"),
  forgotImage: require("../assets/images/forgot.png"),
  check: require("../assets/images/check.png"),
  onboarding1: require("./../assets/images/onboarding1.png"),
  onboarding2: require("./../assets/images/onboarding2.png"),
  banner1: require("./../assets/images/banner1.png"),
  banner2: require("./../assets/images/banner2.png"),
  product1: require("./../assets/images/product1.png"),
  product2: require("./../assets/images/product2.png"),
  product3: require("./../assets/images/product3.png"),
  product4: require("./../assets/images/product4.png"),
  avatar: require("./../assets/images/avatar.png"),
  settings: require("./../assets/images/settings.png"),
  menu: require("./../assets/images/menu.png"),
  nodata: require("../assets/images/nodata.png"),
  logout: require("../assets/images/logout.png"),
  deleteaccount: require("../assets/images/deleteaccount.png"),
  changepass: require("../assets/images/changepass.png"),
};
